---

- name: Deploy Symfony Demo Application
  hosts: all
  remote_user: root
  gather_facts: false
  vars_files:
    - ../vars/default.yml
    - ../vars/secrets.yml
  roles:
    - { role: "setup", tags: "setup" }
    - { role: "nginx", tags: "nginx" }
    - { role: "php", tags: "php" }
    - { role: "mysql", tags: "mysql" }
    - { role: "composer", tags: "composer" }
    - { role: "application", tags: "application" }
    - { role: "check-http", tags: "check-http" }
