name: Ansible CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint ansible playbook
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r symfony-lemp_ubuntu20.04/requirements.txt
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.mysql

      - name: Lint python module with Flake8
        run: flake8 symfony-lemp_ubuntu20.04/playbooks/library/

      - name: Set ansible config secrets
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run:
          echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password

      - name: Display version
        run: ansible-lint --version
      
      - name: Lint main playbook
        run: ansible-playbook --syntax-check -i symfony-lemp_ubuntu20.04/inventory --vault-password-file .ansible-vault-password symfony-lemp_ubuntu20.04/playbooks/main.yml

      - name: Lint http_status playbook
        run: ansible-playbook --syntax-check -i symfony-lemp_ubuntu20.04/inventory --vault-password-file .ansible-vault-password symfony-lemp_ubuntu20.04/playbooks/http_status.yml

      - name: Lint count_post playbook
        run: ansible-playbook --syntax-check -i symfony-lemp_ubuntu20.04/inventory --vault-password-file .ansible-vault-password symfony-lemp_ubuntu20.04/playbooks/count_post.yml
      
      - name: Lint inventory playbook
        run: ansible-playbook --syntax-check -i symfony-lemp_ubuntu20.04/inventory --vault-password-file .ansible-vault-password symfony-lemp_ubuntu20.04/playbooks/inventory.yml
